language: node_js
node_js:
  - "7"
  - "6"
  - "4"
git:
  depth: 10000 # need the whole thing
after_script:
  - "./node_modules/.bin/tap --coverage --coverage-report=text-lcov | ./node_modules/.bin/codacy-coverage"
