language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
git:
  depth: 10000 # need the whole thing
after_script:
  - "./node_modules/.bin/tap --coverage --coverage-report=text-lcov | ./node_modules/.bin/codacy-coverage"
